#pragma once

#include <cstdint>

namespace Spieler
{

    // Using Win32 virtual key codes
    enum KeyCode : std::int32_t
    {
        KeyCode_Unknown         = -1,

        KeyCode_Backspace       = 0x08,
        KeyCode_Tab             = 0x09,
        KeyCode_Enter           = 0x0D,
        KeyCode_Shift           = 0x10,
        KeyCode_Control         = 0x11,
        KeyCode_Alt             = 0x12,
        KeyCode_CapsLock        = 0x14,
        KeyCode_Escape          = 0x1B,

        KeyCode_Space           = 0x20,
        KeyCode_PageUp          = 0x21,
        KeyCode_PageDown        = 0x22,
        KeyCode_End             = 0x23,
        KeyCode_Home            = 0x24,
        KeyCode_LeftArrow       = 0x25,
        KeyCode_UpArrow         = 0x26,
        KeyCode_RightArrow      = 0x27,
        KeyCode_DownArrow       = 0x28,
        KeyCode_Select          = 0x29,
        KeyCode_Print           = 0x2A,
        KeyCode_Execute         = 0x2B,
        KeyCode_Snapshot        = 0x2C,
        KeyCode_Insert          = 0x2D,
        KeyCode_Delete          = 0x2E,
        KeyCode_Help            = 0x2F,

        KeyCode_D0              = 0x30,
        KeyCode_D1              = 0x31,
        KeyCode_D2              = 0x32,
        KeyCode_D3              = 0x33,
        KeyCode_D4              = 0x34,
        KeyCode_D5              = 0x35,
        KeyCode_D6              = 0x36,
        KeyCode_D7              = 0x37,
        KeyCode_D8              = 0x38,
        KeyCode_D9              = 0x39,

        KeyCode_A               = 0x41,
        KeyCode_B               = 0x42,
        KeyCode_C               = 0x43,
        KeyCode_D               = 0x44,
        KeyCode_E               = 0x45,
        KeyCode_F               = 0x46,
        KeyCode_G               = 0x47,
        KeyCode_H               = 0x48,
        KeyCode_I               = 0x49,
        KeyCode_J               = 0x4A,
        KeyCode_K               = 0x4B,
        KeyCode_L               = 0x4C,
        KeyCode_M               = 0x4D,
        KeyCode_N               = 0x4E,
        KeyCode_O               = 0x4F,
        KeyCode_P               = 0x50,
        KeyCode_Q               = 0x51,
        KeyCode_R               = 0x52,
        KeyCode_S               = 0x53,
        KeyCode_T               = 0x54,
        KeyCode_U               = 0x55,
        KeyCode_V               = 0x56,
        KeyCode_W               = 0x57,
        KeyCode_X               = 0x58,
        KeyCode_Y               = 0x59,
        KeyCode_Z               = 0x5A,

        KeyCode_LeftWin         = 0x5B,
        KeyCode_RightWin        = 0x5C,
        KeyCode_Apps            = 0x5D,
        KeyCode_Sleep           = 0x5F,
        KeyCode_Numpad0         = 0x60,
        KeyCode_Numpad1         = 0x61,
        KeyCode_Numpad2         = 0x62,
        KeyCode_Numpad3         = 0x63,
        KeyCode_Numpad4         = 0x64,
        KeyCode_Numpad5         = 0x65,
        KeyCode_Numpad6         = 0x66,
        KeyCode_Numpad7         = 0x67,
        KeyCode_Numpad8         = 0x68,
        KeyCode_Numpad9         = 0x69,
        KeyCode_Multiply        = 0x6A,
        KeyCode_Add             = 0x6B,
        KeyCode_Separator       = 0x6C,
        KeyCode_Subtract        = 0x6D,
        KeyCode_Decimal         = 0x6E,
        KeyCode_Divide          = 0x6F,

        KeyCode_F1              = 0x70,
        KeyCode_F2              = 0x71,
        KeyCode_F3              = 0x72,
        KeyCode_F4              = 0x73,
        KeyCode_F5              = 0x74,
        KeyCode_F6              = 0x75,
        KeyCode_F7              = 0x76,
        KeyCode_F8              = 0x77,
        KeyCode_F9              = 0x78,
        KeyCode_F10             = 0x79,
        KeyCode_F11             = 0x7A,
        KeyCode_F12             = 0x7B,
        KeyCode_F13             = 0x7C,
        KeyCode_F14             = 0x7D,
        KeyCode_F15             = 0x7E,
        KeyCode_F16             = 0x7F,
        KeyCode_F17             = 0x80,
        KeyCode_F18             = 0x81,
        KeyCode_F19             = 0x82,
        KeyCode_F20             = 0x83,
        KeyCode_F21             = 0x84,
        KeyCode_F22             = 0x85,
        KeyCode_F23             = 0x86,
        KeyCode_F24             = 0x87,

        KeyCode_NumLock         = 0x90,
        KeyCode_Scroll          = 0x91,

        KeyCode_LeftShift       = 0xA0,
        KeyCode_RightShift      = 0xA1,
        KeyCode_LeftControl     = 0xA2,
        KeyCode_RightControl    = 0xA3,
        KeyCode_LeftAlt         = 0xA4,
        KeyCode_RightAlt        = 0xA5,
        
        KeyCode_VolumeMute      = 0xAD,
        KeyCode_VolumeDown      = 0xAE,
        KeyCode_VolumeUp        = 0xAF,

        KeyCode_MediaNextTrack  = 0xB0,
        KeyCode_MediaPrevTrack  = 0xB1,
        KeyCode_MediaStop       = 0xB2,
        KeyCode_MediaPlayPause  = 0xB3
    };

} // namespace Spieler